all: buffsize100 buffsize4096 buffsize8192 buffsize16384

buffsize100: fig3_5.c
	gcc fig3_5.c -o buffsize100
buffsize4096: fig3_5.c
	gcc fig3_5.c -o buffsize4096
buffsize8192: fig3_5.c
	gcc fig3_5.c -o buffsize8192
buffsize16384: fig3_5.c
	gcc fig3_5.c -o buffsize16384
